filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - ${report_path}/*.json
    # important to configure the json mode and recover filebeat errors
    json.add_error_key: true
    tags: ["gravitee_json"]

output.logstash:
  hosts: ["logstash:5044"]
