version: '3.3'
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:${elasticsearch_version}
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    stdin_open: true
    tty: true
    network_mode: bridge
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "50"
  kibana:
    container_name: kibana
    image: kibana:${elasticsearch_version}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 5601:5601
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    stdin_open: true
    tty: true
    network_mode: bridge
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "50"
  logstash:
    container_name: logstash
    image: logstash:${elasticsearch_version}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${gravitee_conf_file}:/usr/share/logstash/pipeline/logstash.conf
      - ${gravitee_templates_path}:/usr/share/logstash/templates
      - ${gravitee_report_path}:/usr/share/gravitee/logs
    ports:
      - 5044:5044
    links:
      - elasticsearch:elasticsearch
    depends_on:
      - elasticsearch
    stdin_open: true
    tty: true
    network_mode: bridge
    environment:
      - report_path=/usr/share/gravitee/logs
      - templates_path=/usr/share/logstash/templates
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "50"
  filebeat:
    user: root
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:${elasticsearch_version}
    links:
      - logstash:logstash
    depends_on:
      - logstash
    environment:
      - report_path=/usr/share/gravitee/logs
    volumes:
      - /var/run/docker.sock:/host_docker/docker.sock
      - /var/lib/docker:/host_docker/var/lib/docker
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ${gravitee_report_path}:/usr/share/gravitee/logs
    command: ["--strict.perms=false"]
    ulimits:
      memlock:
        soft: -1
        hard: -1
    stdin_open: true
    tty: true
    network_mode: bridge
    deploy:
      mode: global
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "50"
